### ISSUE TITLE
Add check messages

### ISSUE THREAD

**Issue by marsam** [Synthetica9/nix-linter#23]
It would be nice that the checks include descriptive messages about what each checker means

Use case: I'm writing a Flycheck checker, but I'm writing the check messages myself https://github.com/marsam/flycheck/commit/acfce5461dc5869502c4f011152ad9622923390f
![image](https://user-images.githubusercontent.com/65531/50233039-87c45900-0380-11e9-9f82-922bd2dad86c.png)

**Comment by Synthetica9** [comment]
Ah, yes, great idea! I'll add an `description` field to the JSON output. 

(Cool that you're writing editor support into BTW!)

**Comment by Synthetica9** [comment]
@marsam eabae01 should fix this.

**Comment by marsam** [comment]
thanks!
