### ISSUE TITLE
master does not build because hnix is marked as broken in the pinned nixpkgs version

### ISSUE THREAD

**Issue by maralorn** [Synthetica9/nix-linter#29]
Actually it‘s all said in the title, the CI fails, too. So I don‘t feel like it’s my mistake.

I‘d love to try `nix-linter`.

**Comment by Synthetica9** [comment]
Correct. I currently do not want to put too much time in this project until [nixfmt](https://github.com/serokell/nixfmt) is a bit more mature, so I can rewrite it based on that. 

However, I will see if I can pin the last nixpkgs commit where this works properly.

**Comment by davidak** [comment]
@Synthetica9 is there some indicator to see when nixfmt is ready like closed issues?

Maybe add it to a status section in the readme? Currently the project looks abandoned.

**Comment by Synthetica9** [comment]
Adding it to the README is probably a good idea, I'll also talk to the authors of Nixfmt to see what they think about it

**Comment by Synthetica9** [comment]
Closed by #31
