### ISSUE TITLE
nix-linter fails to build in upstream NixPkgs

### ISSUE THREAD

**Issue by bhipple** [Synthetica9/nix-linter#33]
It's failing to build in the upstream NixPkgs distribution to a broken `hnix`, though the `nix-build -A nix-linter` here works.  Is it intended to be usable out of NixPkgs or should we stick to just using it here?

**Comment by sorki** [comment]
`hnix 0.8` is now available in nixpkgs, should be good from now on - might not even need porting but I need to take a closer look.
