### ISSUE TITLE
Binary cache not up to date?

### ISSUE THREAD

**Issue by cprussin** [Synthetica9/nix-linter#35]
Hi!

It seems the cachix binary cache is not up to date?  I think it would help to configure some github actions on a cron to keep building & updating the binary cache as nixpkgs gets released.

I'd be happy to submit a PR to add the relevant actions, but to get it to work I'd need access to add the right secrets, or I'd need you to add a secret for the signing key and give me the name of the secret.

I can't tell if this package is still maintained or not since it doesn't look like there's been any activity in a while--if you don't still maintain it I'd be happy to take over as a maintainer as I use this quite a bit :)

Thanks!

**Comment by domenkozar** [comment]
cc @Synthetica9

**Comment by expipiplus1** [comment]
@Synthetica9 If you add the cachix private key to a secret in this repo can have the CI keep the cachix cache up to date.

**Comment by expipiplus1** [comment]
ah, what is the key for it?

**Comment by Synthetica9** [comment]
`CACHIX_PRIVATE_KEY`

**Comment by expipiplus1** [comment]
thanks!

**Comment by expipiplus1** [comment]
Closed by  #55

**Comment by cprussin** [comment]
Very exciting, thanks so much!
