### ISSUE TITLE
Update to hnix 0.9.1

### ISSUE THREAD

**Issue by domenkozar** [Synthetica9/nix-linter#36]
As nix-linter doesn't build on nixpkgs master.

**Comment by domenkozar** [comment]
cc @Synthetica9

**Comment by Synthetica9** [comment]
Sorry, maintaining this project has been very low down my list of priorities, and it will remain that way for at least a couple of months. From what I gathered, the move to a newer hnix would not necessarily be trivial. 

I see a few options here:

* Removal from pre-commit-hooks.nix. (I assume that would fix your problem)
* Someone else doing the update. I'd be fine with handing over ownership of this repo, adding a maintainer or endorsing a fork. Problem here is that there'd need to be a volunteer for this.
* Wait until I eventually get to it.

**Comment by sorki** [comment]
PTAL @#40
