### ISSUE TITLE
LetBraces, redundant, rare, presumably old syntax

### ISSUE THREAD

**Issue by roberth** [Synthetica9/nix-linter#47]
I found [this](https://github.com/NixOS/nix/blob/258e5338d68c5d98090748bbbd49bd33a37c7954/tests/dependencies.nix#L3) in the Nix test suite:

```
let {
  x = 1;
  body = x;
}
```

I've never noticed it before and I've been editing a lot of Nix code.
This construct is redundant and `body` is a completely arbitrary non-keyword. No-one should use it.

Here's a parser production for it. It's desugared immediately to `(rec { }).body`. I've also pasted `REC` for reference.

```
  | LET '{' binds '}'
    { $3->recursive = true; $$ = new ExprSelect(noPos, $3, data->symbols.create("body")); }
  | REC '{' binds '}'
    { $3->recursive = true; $$ = $3; }
```

**Comment by Synthetica9** [comment]
This would have to be fixed in hnix, not here. Closing for now.
