### ISSUE TITLE
Add ability to disable checks at command line

### ISSUE THREAD

**Issue by lunik1** [Synthetica9/nix-linter#50]
As far as I can work out that while optional checks can be enabled by `-W` at the command line, there is no way of disabling checks that are enabled by default. It would be useful to be able to disable such checks n cases where you have too many false positives, or are just otherwise uninterested in that specific case.

When using `-W` I expected only the checks I specified to be enabled, however I appreciate changing this behaviour now would be a breaking change and inconvenient in many use cases. Perhaps there could be another flag that disables checks and takes precedence over `-W`?

**Comment by Synthetica9** [comment]
It's been a while since I've worked on this, but if I recall correctly you can prefix `no-` to any check to disable it

**Comment by lunik1** [comment]
Yes, that works. Thanks! Is this documented anywhere?
