### ISSUE TITLE
Check for cmake in buildInputs and warn that it should probably be in nativeBuildInputs

### ISSUE THREAD

**Issue by kjeremy** [Synthetica9/nix-linter#60]

**Comment by expipiplus1** [comment]
doesn't seem wild, although this kind of thing would be better served by a "nixpkgs-linter" tool perhaps.

**Comment by Synthetica9** [comment]
Yeah, nix-linter currently only checks for "structural" issues, i.e. things not specific to any one Nix project. I'm gonna this for now, but ideas like this definitely could go in a nixpkgs-specific linter.
